### ISSUE TITLE
Adapting a mesh using firedrake.meshadapt.adapt

### ISSUE THREAD

**Issue by ddundo** [pyroteus/pyroteus#102]
Hei Joe, I may be missing something obvious here, but I was wondering if the `firedrake.meshadapt.adapt` function is implemented as intended and if you could provide some guidance. In your turbine_adapt and desal_adapt test cases (from Nov 2021) I see that you use it and provide, for example, a metric obtained from `pyroteus.metric.hessian_metric`.

This won't work on branch [jwallwork23/parmmg-metric-based](https://github.com/firedrakeproject/firedrake/tree/jwallwork23/parmmg-metric-based) because the metrics from `pyroteus.metric` are not a `RiemannianMetric` class.

I tried to find changes to this but can't seem to find the right branches of firedrake and pyroteus when this stopped working. Is there a new preferred function for adapting?

**Comment by jwallwork23** [comment]
Hi @ddundo. I'm afraid this stuff is out of date and is in the process of being updated. Previously, metrics were just treated as `Function`s from a `TensorFunctionSpace`. This was what was used in `desal_adapt` and `turbine_adapt`. Now we are moving towards using the `RiemannianMetric` class instead, since it already implements a lot of the functionality that's in `pyroteus.metric` for plain `Function`s. See #52. Also note that the Firedrake branch used to look quite different, but you should be able to find an archived version of `jwallwork23/metric-based` from the Zenodo records referenced in my papers.

So I guess the summary is that `pyroteus.metric` is in the process of being updated to use `RiemannianMetric`s. This has mainly not been done due to lack of time, but is on my To Do list. Let me know if there is something important you think I should focus on. If there's anything you can help with, that would be amazing and pull requests are very much appreciated :)

**Comment by ddundo** [comment]
Thanks @jwallwork23! I did see recent commits to it so I was wondering if I was missing some in-between step. So far I've just adapted it to work, but sometimes I run into problems. I'll keep an eye on it!

And yes, I can clean up some of my code that fixes some things re to fixed point iteration and ask you to review it next week :)

**Comment by jwallwork23** [comment]
Great, let's meet to chat about this soon. I have been busy the past couple of weeks but should have more time to work on Pyroteus again now.

**Comment by jwallwork23** [comment]
@ddundo note that some of the metric processing functions are implemented in C++ and can be found in [this subdirectory](https://github.com/pyroteus/pyroteus/tree/main/pyroteus/cxx), as mentioned in the meeting yesterday.

**Comment by ddundo** [comment]
Ah thanks @jwallwork23 ! I didn't realise this was the same thing.

**Comment by jwallwork23** [comment]
A lot of this stuff will go away once I finish moving metric functionality to the Firedrake branch.
