### ISSUE TITLE
Fix UFL attribute error

### ISSUE THREAD

**Issue by jwallwork23** [pyroteus/pyroteus#91]
``ufl.Product does not have attribute flat``

**Comment by jwallwork23** [comment]
@ddundo please could you remind me where this error came up so I can chase it down? Thanks

**Comment by jwallwork23** [comment]
Or if you have a fix that'd be even better :)

**Comment by ddundo** [comment]
I am somewhat sure that when I first encountered this that this would reproduce the error:
```
from firedrake import Constant
prod = Constant(1) * Constant(1)
prod.flat
```

but it's not the case now! Maybe I am misremembering or it's due to the change of the firedrake branches? At the time I was using metric-based branch and now I am on parmmg-metric-based (which I see you updated in the install scripts today).

Anyway, the only time I encounter this is when I try to run [this Icepack example](https://icepack.github.io/notebooks/how-to/03-adaptivity/) exactly as it is but with also importing pyroteus.  Then I get a warning 
```
/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/adjoint/constant.py:44: UserWarning: Could not find overloaded class of type '<class 'ufl.algebra.Product'>'.
  other = create_overloaded_object(other)
```
and the error is raised here:
```
File "/home/ubuntu/software/firedrake-adapt/src/pyadjoint/dolfin_adjoint_common/blocks/constant.py", line 39, in __init__
    for i, v in enumerate(other.flat):
AttributeError: 'Product' object has no attribute 'flat'
```

I don't get this warning if I only load firedrake, without pyroteus.

**Comment by ddundo** [comment]
I am pretty sure that when I first encountered this that this would also reproduce the error
```
from firedrake import Constant
import pyroteus

prod = Constant(1) * Constant(1)
prod.flat
```

but now I get the error when I only import firedrake. Most likely I am misremembering or maybe it's due to the change of firedrake branch? At the time I was using metric-based and now I am on the parmmg-metric-based branch (which I saw you updated in the install scripts today).

**Comment by jwallwork23** [comment]
Okay. If the issue has gone away with the current setup then can we close this issue?

**Comment by ddundo** [comment]
I still get the error in my first comment, but it's the only time I've seen it so not sure how important it is.

Although, I get a similar warning with `enforce_element_constraint` function: `/home/ubuntu/software/firedrake-adapt/src/firedrake/firedrake/adjoint/function.py:129: UserWarning: Could not find overloaded class of type '<class 'int'>'.
  other = create_overloaded_object(other)`. I only get a warning but no errors. So maybe it's worth investigating? Not sure :)

**Comment by jwallwork23** [comment]
That looks like a different warning. Please could you open a new issue based on the one you just reported regarding `enforce_element_constraint` and then close this one? Thanks.
