### ISSUE TITLE
Move `AdaptParameters` and co to a separate file

### ISSUE THREAD

**Issue by jwallwork23** [pyroteus/pyroteus#97]
Currently `AdaptParameters` and its subclasses reside in `mesh_seq.py`, `metric.py` and `go_mesh_seq.py`.

It would be better to put them in a separate file and test them (see #95).

**Comment by ddundo** [comment]
Hei! This now causes an error by default when doing goal oriented adaptivity: `AttributeError: 'AdaptParameters' object has no attribute 'qoi_rtol'` due to `self.params = kwargs.get("parameters", AdaptParameters())` in initialising MeshSeq. Might be better to pass `GoalOrientedParameters` by default to AdjointMeshSeq? :)
